### PR TITLE
Added .itermcolors

### PR DESCRIPTION
**Pull request by RowanKaag**

### CODE REVIEW

**Comment by inket** [comment]
Not sure the colors are correct. I installed iTerm 2.9 and loaded the colors preset, and it looked like this:

screen shot 2016-04-20 at 10 03 20pm

**Comment by RowanKaag** [comment]
you're right. I had the files mixed up. New commit is in place.

**Comment by inket** [comment]
Isn't correct either.

screen shot 2016-04-20 at 10 42 22pm

so I recreated it myself:

screen shot 2016-04-20 at 10 43 21pm

Will add it to the repo in a few minutes. Closing this pull request.

**Comment by RowanKaag** [comment]
Odd, looks fine to me.

schermafbeelding 2016-04-20 om 15 46 26

**Comment by inket** [comment]
Hmm, odd indeed. For the one I added, I copied the hex values exactly as they are so that should be fine.

**Comment by RowanKaag** [comment]
Looks very much like the Ubuntu skin now. Not sure if that's in iTerm2 by default.

schermafbeelding 2016-04-20 om 15 57 57

**Pull request closed without merging**
